### ISSUE TITLE
Explore Github CI Tools

### ISSUE THREAD

**Issue by tiltec** [yunity/yunity#3]
Github seems to provide Continous Integration tools as a service. We should explore those or set up our own build server.
https://github.com/integrations/feature/code

**Comment by nicksellen** [comment]
circleci is setup now :) just make yourself an account at https://circleci.com/ and your github permissions for yunity repos will let you access all the config stuff (although I put it all in `circle.yml` files in the relevent repos.

Currently I set up 3 repos for CI:
- yunity-webapp-mobile: status: operational, builds, runs tests, and collects artificats
- yunity-core: runs, but has errors because the code is in flux
- yunity-sockets: not sure, probably doesn't do much. no tests I think.
